#name of the workflow
name: Shell Commands

#events
on: [push]

#jobs
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "hello wworld"
      - name: multiline script
        run: |
          npm -v
          node -v
